language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

env:
  - CARGO_FEATURES=""
  - CARGO_FEATURES="std"
  - CARGO_FEATURES="std use_complex"

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt-preview && cargo fmt -- --version

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --features "$CARGO_FEATURES"
  - cargo test --features "$CARGO_FEATURES"
