language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

env:
  - CARGO_FEATURES=""
  - CARGO_FEATURES="std"
  - CARGO_FEATURES="std use_complex"

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - cargo build --verbose

script:
  - cargo build --verbose --features "$CARGO_FEATURES"
  - cargo test --verbose --features "$CARGO_FEATURES"
